INSERT INTO TB_PRODUCTS(NAME, DESCRIPTION, PRICE, IMAGE_URL) VALUES ('Notebook Dell', 'I9, 16GB - 1TB, SDD', 4500.00, NULL);
INSERT INTO TB_PRODUCTS(NAME, DESCRIPTION, PRICE, IMAGE_URL) VALUES ('Notebook Macbook', 'I7, 16GB - 1TB, SDD', 14500, NULL);
INSERT INTO TB_PRODUCTS(NAME, DESCRIPTION, PRICE, IMAGE_URL) VALUES ('SmartApple', 'I&, 16GB - 1TB, SDD', 6500.00, NULL);

INSERT INTO TB_CATEGORY (NAME) VALUES ('Eletronics');
INSERT INTO TB_CATEGORY (NAME) VALUES ('Books');
INSERT INTO TB_CATEGORY (NAME) VALUES ('SmartWatchs');

INSERT INTO TB_PRODUCTS_CATEGORYS (PRODUCT_ID, CATEGORY_ID) VALUES (1, 2);
INSERT INTO TB_PRODUCTS_CATEGORYS (PRODUCT_ID, CATEGORY_ID) VALUES (2, 2);
INSERT INTO TB_PRODUCTS_CATEGORYS (PRODUCT_ID, CATEGORY_ID) VALUES (3, 1);

