INSERT INTO TB_ORDERS (MOMENT, ORDER_NUMBER) VALUES ('2021-01-16T18:34:23Z', 3454959);
INSERT INTO TB_ORDERS (MOMENT, ORDER_NUMBER) VALUES ('2021-01-16T21:34:56Z', 9483854);
INSERT INTO TB_ORDERS (MOMENT, ORDER_NUMBER) VALUES ('2021-01-16T19:45:23Z', 8932984);

INSERT INTO TB_COMPUTERS(NAME, DESCRIPTION, COLOR, SERIE_NUMBER, BRAND, MODEL, QUANTITY, PRICE, HEIGTH, WIDTH) VALUES ('Notebook Mac Book Air', 'Ultra wild with a focus on performance for your processing skills', 'Write', '98434', 'Apple', 'Pró', 1, 18.000, 13.0, 16.00);
INSERT INTO TB_COMPUTERS(NAME, DESCRIPTION, COLOR, SERIE_NUMBER, BRAND, MODEL, QUANTITY, PRICE, HEIGTH, WIDTH) VALUES ('Notebook Mac Book', 'Ultra wild with a focus on performance for your processing skills', 'Gray', '93294', 'Apple', 'Pró', 1, 12.000, 13.0, 15.00);
INSERT INTO TB_COMPUTERS(NAME, DESCRIPTION, COLOR, SERIE_NUMBER, BRAND, MODEL, QUANTITY, PRICE, HEIGTH, WIDTH) VALUES ('Notebook Dell Inspirion', 'High performance in memory and availability', 'Black', '98654', 'Dell', 'Pró', 2, 10.000, 14.0, 18.00);

INSERT INTO TB_ORDERS_COMPUTERS (ORDER_ID, COMPUTER_ID) VALUES (1, 2);
INSERT INTO TB_ORDERS_COMPUTERS (ORDER_ID, COMPUTER_ID) VALUES (2, 2);
INSERT INTO TB_ORDERS_COMPUTERS (ORDER_ID, COMPUTER_ID) VALUES (3, 2);
INSERT INTO TB_ORDERS_COMPUTERS (ORDER_ID, COMPUTER_ID) VALUES (3, 3);