INSERT INTO TB_USERS (NAME, EMAIL, CPF, PASSWORD) VALUES ('Bob', 'bob@gmail.com', '98328394244', '$2a$10$X6HHDVpa4OaM./BjOCfl/OuyeHKU5ORCT45qbZFJnf46nWuSyFJMK');
INSERT INTO TB_USERS (NAME, EMAIL, CPF, PASSWORD) VALUES ('Alex', 'alex@gmail.com', '89328993232', '$2a$10$GhsHkf1g0MP6hhFQYwDH8.HTLB.snLz5DLqeQrxc1fX3dU8lF2tpi');
INSERT INTO TB_USERS (NAME, EMAIL, CPF, PASSWORD) VALUES ('Chris', 'chris@gmail.com', '98437832748', '$2a$10$HeuYiPhks9ShlIMval/OPeOxifJV0tLkILpftQCqcnGBBl6hn9nIa');

INSERT INTO TB_ROLES (ROLE_NAME) VALUES ('ROLE_OPERATOR');
INSERT INTO TB_ROLES (ROLE_NAME) VALUES ('ROLE_ADM');

INSERT INTO TB_USERS_ROLES (USER_ID, ROLE_ID) VALUES (1, 1);
INSERT INTO TB_USERS_ROLES (USER_ID, ROLE_ID) VALUES (2, 1);
INSERT INTO TB_USERS_ROLES (USER_ID, ROLE_ID) VALUES (2, 2);